#!/bin/bash

if [ -n "$(pidof Xtightvnc)" ]; then
    xhost + > /dev/null 2>&1
fi
sudo mount -t cgroup2 cgroup2 /sys/fs/cgroup > /dev/null 2>&1
sudo mount -t securityfs securityfs /sys/kernel/security/ > /dev/null 2>&1

sudo -u ubuntu chromium-browser > /dev/null 2>&1 &